name: danak
description: "financial management app"

publish_to: 'none'


version: 1.4.5

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  get: ^4.7.3
  flutter_localizations:
    sdk: flutter
  hugeicons: ^1.1.4
  flutter_staggered_animations: ^1.1.1
  animated_text_kit: ^4.3.0
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.2
  flutter_screenutil: ^5.9.3
  salomon_bottom_bar: ^3.3.2
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3
  animations: ^2.1.1
  flutter_spinkit: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: IranYekan
      fonts:
        - asset: assets/fonts/IRANYekanRegularFaNum.ttf
          weight: 400
        - asset: assets/fonts/IRANYekanMediumFaNum.ttf
          weight: 500
        - asset: assets/fonts/IRANYekanBoldFaNum.ttf
          weight: 600
        - asset: assets/fonts/IRANYekanBlackFaNum.ttf
          weight: 700

